package com.csierra.demo03072025.persistence;

import org.springframework.stereotype.Component;

import java.util.Set;

import static com.csierra.demo03072025.persistence.AppointmentState.CREATED;
import static com.csierra.demo03072025.persistence.AppointmentState.NOTIFIED;

@Component
//Note: mocking persistence, but this is meant to correspond to a DB owned by this microservice
public class AppointmentRepository /* extends JpaRepository<Appointment, Long> */{

    /**
     * This should take a search request, use it to construct a query to be run against a database managed by this
     * repository and then return an Optional, or return an Appointment that could be null. Since we are mocking
     * external dependencies, instead I'm using userId to determine whether we want to show the case where
     * an appointment already exists, or create a new one
     */
    public Appointment findExistingAppointment(AppointmentRequest request) {
        //In actuality, this should search a repository (corresponding to a DB managed by this service) for existing appointments
        if (Set.of(CREATED.toString(), NOTIFIED.toString()).contains(request.getUserId())) {
            return buildAppointment(request, AppointmentState.valueOf(request.getUserId()));
        }

        return null;
    }

    private Appointment buildAppointment(AppointmentRequest request, AppointmentState expectedState) {
        return Appointment.builder()
                .id("appointmentId") // this would be a primary key generated by the DB upon entity creation
                .userId(request.getUserId())
                .propertyId(request.getPropertyId())
                .appointmentTime(request.getAppointmentTime())
                .officeId(request.getOfficeId())
                .agentId(request.getAgentId())
                .appointmentState(expectedState)
                .build();
    }

    public Appointment createNewAppointment(AppointmentRequest request) {
        return buildAppointment(request, CREATED);
    }
}
